# https://taskfile.dev

version: '3'

vars:
  KUBECTL: kubectl --context=k3d-local
  KUBEAPPLY: "{{.KUBECTL}} apply"
  KUSTOMIZE: "{{.KUBEAPPLY}} --kustomize"
  KUBEWAIT: "{{.KUBECTL}} wait"
  KUBEWAIT_AVAIL: "{{.KUBEWAIT}} --for=condition=available"
  KUBEWAIT_READY: "{{.KUBEWAIT}} --for=condition=ready"
  KUBECREATE: "{{.KUBECTL}} create -o yaml --dry-run=client"
  KN: kn --context=k3d-local

tasks:
  default:
    cmds:
    - task -l
    silent: true

  create:
    desc: create k3d cluster
    cmds:
    - k3d cluster create --config=cluster/config.yaml
    - "{{.KUBEWAIT_AVAIL}} --timeout=120s -n kube-system deployment/coredns"

  destroy:
    desc: destroy k3d cluster
    cmds:
    - k3d cluster delete local

  start:
    desc: starts knative environment
    cmds:
    - k3d cluster start local

  stop:
    desc: stop knative environment
    cmds:
    - k3d cluster stop local

  operator:
    desc: install knative operator
    cmds:
    - "{{.KUSTOMIZE}} cluster/operator"
    - "{{.KUBEWAIT_AVAIL}} --timeout=120s -n kube-system deployment/knative-operator"

  knative:
    desc: install knative serving/eventing
    cmds:
    - "{{.KUSTOMIZE}} cluster/knative"
    - "{{.KUBEWAIT_READY}} --timeout=300s -n knative-eventing knativeeventing/eventing"
    - "{{.KUBEWAIT_READY}} --timeout=300s -n knative-serving knativeserving/serving"

  bootstrap:
    desc: bootstrap local knative environment
    cmds:
    - task: create
    - task: operator
    - task: knative

  extras:broker:
    desc: "install extra: default broker"
    cmds:
    - "{{.KN}} broker create default || true"

  extras:apiserver:
    desc: "install extra: k8s apiserver source"
    deps: [extras:broker]
    cmds:
    - "{{.KUBECREATE}} serviceaccount apiserver-source"
    - |
      {{.KUBECREATE}} clusterrole default-eventing-event-observer \
        --resource=events --verb=get,list,watch \
        | {{.KUBEAPPLY}} -f -
    - |
      {{.KUBECREATE}} clusterrolebinding default:apiserver-source:default-eventing-event-observer \
        --clusterrole default-eventing-event-observer \
        --serviceaccount default:apiserver-source \
        | {{.KUBEAPPLY}} -f -
    - |
      {{.KN}} source apiserver create apiserver-source \
        --resource Event:v1 --sink broker:default \
        --service-account apiserver-source || true

  extras:player:
    desc: "install extra: cloudevents-player"
    deps: [extras:broker]
    cmds:
    - |
      {{.KN}} service create cloudevents-player \
        --image ruromero/cloudevents-player:latest \
        --env BROKER_URL=http://broker-ingress.knative-eventing.svc.cluster.local/default/default

  extras:display:
    desc: "install extra: event-display"
    deps: [extras:broker]
    cmds:
    - |
      {{.KN}} service create event-display \
        --image gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
    - |
      {{.KN}} trigger create broker-to-event-display \
        --sink ksvc:event-display
