---
# k3d cluster create local --config=cluster/config.yaml
apiVersion: k3d.io/v1alpha3
kind: Simple
name: knative
image: rancher/k3s:v1.23.1-k3s1
options:
  k3d:
    wait: true
  k3s:
    extraArgs:
    - arg: --disable=traefik
      nodeFilters:
      - server:*
ports:
- port: 80:80
  nodeFilters:
  - servers:*:proxy
  - agents:*:proxy
- port: 443:443
  nodeFilters:
  - servers:*:proxy
  - agents:*:proxy
# registries:
#   use:
#   - k3d-knative-registry:5000
#   config: |
#     mirrors:
#       r.vcap.me:
#         endpoint:
#         - http://k3d-knative-registry:5000
